### ISSUE TITLE
[Suggestion] 关于软件的一点建议

### ISSUE THREAD

**Issue by zxp19821005** [easyhutu/any-sync-gui#1]
如题。
我已经将该软件移植到了ArchLinux的AUR：https://aur.archlinux.org/packages/any-sync-gui
目前我的系统上已经安装了electron25，按照`PKGBUILD`相关打包准则，我计划只保留`resources`目录下相关内容，但是在`resources`目录下运行时报错：(我已经申明了路径：`export PATH="./:$PATH"`)
```
$ electron25 app.asar
cfg file /usr/lib/electron25/resources/any_sync_cfg.json
resource path /usr/lib/electron25/resources/resources, dist path: /usr/lib/electron25/resources/dist
set k, v sysInfo {
  resource: '/usr/lib/electron25/resources/resources',
  dist: '/usr/lib/electron25/resources/dist',
  listenPort: 8081,
  env: undefined
}
resources path err: Error: EACCES: permission denied, mkdir '/usr/lib/electron25/resources/resources'
    at Object.mkdirSync (node:fs:1396:3)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/server/config.js:21:12)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/server/servive/ping.js:3:20) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/lib/electron25/resources/resources'
}
[644953:1205/103018.874582:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[644953:1205/103018.874918:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
write cfg err: [Error: EACCES: permission denied, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/lib/electron25/resources/any_sync_cfg.json'
}
read cfg err: [Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/lib/electron25/resources/any_sync_cfg.json'
}
read cfg err: [Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/lib/electron25/resources/any_sync_cfg.json'
}
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'toString')
    at ReadFileContext.callback (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/server/utils/kvStore.js:70:37)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:325:13)
(node:644953) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:644953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:644953) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/usr/lib/electron25/resources/public/icons.iconset/icon_16x16.png'
    at initTray (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/main.js:21:21)
    at createWindow (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/main.js:60:5)
    at /home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/main.js:67:5
(node:644953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```
我本人不太会编程，根据相关提示内容，查找到调用`any_sync_cfg.json`的代码在`electron_gui/server/utils/kvStore.js`这个文件中；
而`icon_16x16.png`所在的文件为`electron_gui/server/main.js`。
这两个文件都定义了路径：
`const path = require('path')`
不知道能不能把这个路径改为相对路径？或者还有没有其他更好的办法？

**Comment by easyhutu** [comment]
> 如题。 我已经将该软件移植到了ArchLinux的AUR：https://aur.archlinux.org/packages/any-sync-gui 目前我的系统上已经安装了electron25，按照`PKGBUILD`相关打包准则，我计划只保留`resources`目录下相关内容，但是在`resources`目录下运行时报错：(我已经申明了路径：`export PATH="./:$PATH"`)
> 
> ```
> $ electron25 app.asar
> cfg file /usr/lib/electron25/resources/any_sync_cfg.json
> resource path /usr/lib/electron25/resources/resources, dist path: /usr/lib/electron25/resources/dist
> set k, v sysInfo {
>   resource: '/usr/lib/electron25/resources/resources',
>   dist: '/usr/lib/electron25/resources/dist',
>   listenPort: 8081,
>   env: undefined
> }
> resources path err: Error: EACCES: permission denied, mkdir '/usr/lib/electron25/resources/resources'
>     at Object.mkdirSync (node:fs:1396:3)
>     at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/server/config.js:21:12)
>     at Module._compile (node:internal/modules/cjs/loader:1269:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
>     at Module.load (node:internal/modules/cjs/loader:1124:32)
>     at Module._load (node:internal/modules/cjs/loader:965:12)
>     at f._load (node:electron/js2c/asar_bundle:2:13377)
>     at Module.require (node:internal/modules/cjs/loader:1148:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at Object.<anonymous> (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/server/servive/ping.js:3:20) {
>   errno: -13,
>   syscall: 'mkdir',
>   code: 'EACCES',
>   path: '/usr/lib/electron25/resources/resources'
> }
> [644953:1205/103018.874582:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
> [644953:1205/103018.874918:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
> write cfg err: [Error: EACCES: permission denied, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'open',
>   path: '/usr/lib/electron25/resources/any_sync_cfg.json'
> }
> read cfg err: [Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/usr/lib/electron25/resources/any_sync_cfg.json'
> }
> read cfg err: [Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/usr/lib/electron25/resources/any_sync_cfg.json'
> }
> A JavaScript error occurred in the main process
> Uncaught Exception:
> TypeError: Cannot read properties of undefined (reading 'toString')
>     at ReadFileContext.callback (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/server/utils/kvStore.js:70:37)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:325:13)
> (node:644953) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'
> (Use `electron --trace-warnings ...` to show where the warning was created)
> (node:644953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:644953) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/usr/lib/electron25/resources/public/icons.iconset/icon_16x16.png'
>     at initTray (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/main.js:21:21)
>     at createWindow (/home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/main.js:60:5)
>     at /home/zxp-endeavouros/.cache/paru/clone/any-sync-gui/src/any-sync-gui-1.3.0/electron_gui/out/Lan同步-linux-x64/resources/app.asar/main.js:67:5
> (node:644953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> ```
> 
> 我本人不太会编程，根据相关提示内容，查找到调用`any_sync_cfg.json`的代码在`electron_gui/server/utils/kvStore.js`这个文件中； 而`icon_16x16.png`所在的文件为`electron_gui/server/main.js`。 这两个文件都定义了路径： `const path = require('path')` 不知道能不能把这个路径改为相对路径？或者还有没有其他更好的办法？

看起来你是在调试模式运行的，在调试模式下需要配置环境变量 NODE_ENV=debug，否则缓存文件路径会错误

**Comment by zxp19821005** [comment]
我是按照`README.md`里面的步骤打包的：
```
cd fe
npm install
npm run build
```
```
cd electron_gui
npm install
npm run make
```
是这里出错了么？
还是只需要在运行脚本里面加入
```
export NODE_ENV=debug
```
即可呢？

**Comment by easyhutu** [comment]
正常情况下，执行打包命令后

```
cd electron_gui
npm install
npm run make
```

在electron_gui目录下面会生成一个./out 文件夹，其中包含了可执行文件，运行可执行文件即可

---

在上面的错误日志中我注意到加载缓存文件的路径出现错误，这是因为在运行时没有正确识别到process.resourcesPath默认资源路径，通常可以通过设置环境变量来解决

**Comment by zxp19821005** [comment]
设置环境变量暂时也无法解决。
### PKGBUILD文件
```
# Maintainer: zxp19821005 <zxp19821005 at 163 dot com>
pkgname=any-sync-gui
_appname="Lan同步"
pkgver=1.3.0
_electronversion=25
pkgrel=4
pkgdesc="一款支持在pc与pc或移动设备之间同步文本信息或文件的应用"
arch=('any')
url="https://github.com/easyhutu/any-sync-gui"
license=('custom')
conflicts=("${pkgname}")
depends=(
    'libxcomposite'
    'libxkbcommon'
    'libxfixes'
    'libcups'
    'mesa'
    'alsa-lib'
    'expat'
    'cairo'
    'libxrandr'
    'pango'
    'libxext'
    'libxcb'
    'at-spi2-core'
    'libdrm'
    'nspr'
    'libxdamage'
    'nss'
    'libx11'
    'gtk3'
)
makedepends=(
    'npm'
    'nodejs'
    'gendesk'
    'git'
)
source=(
    "${pkgname}-${pkgver}::git+${url}.git#tag=v${pkgver}"
    "${pkgname}.sh"
)
sha256sums=('SKIP'
            '8915ca75d453698df81f7f3305cce6869f4261d754d90f0c3724b73c7b24ca84')
build() {
    sed -e "s|@electronversion@|${_electronversion}|" \
        -e "s|@appname@|${pkgname}|g" \
        -e "s|@appasar@|app.asar|g" \
        -i "${srcdir}/${pkgname}.sh"
    gendesk -f -n -q --categories "Utility" --name "${_appname}" --exec "${pkgname}" #--no-sandbox %U"
    export npm_config_build_from_source=true
    export npm_config_cache="${srcdir}/.npm_cache"
    export ELECTRON_SKIP_BINARY_DOWNLOAD=1
    export SYSTEM_ELECTRON_VERSION="$(electron${_electronversion} -v | sed 's/v//g')"
    export ELECTRONVERSION="${_electronversion}"
    cd "${srcdir}/${pkgname}-${pkgver}/fe"
    npm install --force
    npm run build
    cd "${srcdir}/${pkgname}-${pkgver}/electron_gui"
    sed '24,27d' -i forge.config.js
    npm install --force
    npm run package
}
package() {
    install -Dm755 "${srcdir}/${pkgname}.sh" "${pkgdir}/usr/bin/${pkgname}"
    install -Dm644 "${srcdir}/${pkgname}-${pkgver}/electron_gui/out/${_appname}-"*/resources/app.asar -t "${pkgdir}/usr/lib/${pkgname}"
    cp -r "${srcdir}/${pkgname}-${pkgver}/electron_gui/out/${_appname}-"*/resources/{dist,public} "${pkgdir}/usr/lib/${pkgname}"
    install -Dm644 "${srcdir}/${pkgname}.desktop" -t "${pkgdir}/usr/share/applications"
    install -Dm644 "${srcdir}/${pkgname}-${pkgver}/electron_gui/public/icon.png" "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
    install -Dm644 "${srcdir}/${pkgname}-${pkgver}/electron_gui/out/${_appname}-"*/LICENSE* -t "${pkgdir}/usr/share/licenses/${pkgname}"
}
```
### any-sync-gui.sh
```
#!/bin/bash
set -e
_APPDIR="/usr/lib/any-sync-gui"
export PATH="${_APPDIR}:${PATH}"
export ELECTRON_IS_DEV=0
export LD_LIBRARY_PATH="${_APPDIR}/swiftshader:${_APPDIR}/lib:${LD_LIBRARY_PATH}"
_ASAR="${_APPDIR}/app.asar"
if [[ $EUID -ne 0 ]] || [[ $ELECTRON_RUN_AS_NODE ]]; then
    cd "${_APPDIR}"
    exec electron25 "${_ASAR}" "$@"
else
    cd "${_APPDIR}"
    exec electron25 "${_ASAR}" --no-sandbox "$@"
fi
```
### 运行结果
```
$ any-sync-gui
cfg file /usr/lib/electron25/resources/any_sync_cfg.json
resource path /usr/lib/electron25/resources/resources, dist path: /usr/lib/electron25/resources/dist
set k, v sysInfo {
  resource: '/usr/lib/electron25/resources/resources',
  dist: '/usr/lib/electron25/resources/dist',
  listenPort: 8081,
  env: undefined
}
resources path err: Error: EACCES: permission denied, mkdir '/usr/lib/electron25/resources/resources'
    at Object.mkdirSync (node:fs:1396:3)
    at Object.<anonymous> (/usr/lib/any-sync-gui/app.asar/server/config.js:21:12)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/usr/lib/any-sync-gui/app.asar/server/servive/ping.js:3:20) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/lib/electron25/resources/resources'
}
[90357:1207/102130.306802:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[90357:1207/102130.306838:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
write cfg err: [Error: EACCES: permission denied, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/usr/lib/electron25/resources/any_sync_cfg.json'
}
read cfg err: [Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/lib/electron25/resources/any_sync_cfg.json'
}
read cfg err: [Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/lib/electron25/resources/any_sync_cfg.json'
}
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'toString')
    at ReadFileContext.callback (/usr/lib/any-sync-gui/app.asar/server/utils/kvStore.js:70:37)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:325:13)
(node:90357) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/usr/lib/electron25/resources/any_sync_cfg.json'
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:90357) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:90357) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/usr/lib/electron25/resources/public/icons.iconset/icon_16x16.png'
    at initTray (/usr/lib/any-sync-gui/app.asar/main.js:21:21)
    at createWindow (/usr/lib/any-sync-gui/app.asar/main.js:60:5)
    at /usr/lib/any-sync-gui/app.asar/main.js:67:5
(node:90357) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
win close
^Cbefore quit...
win close
```

**Comment by zxp19821005** [comment]
或者这个环境变量不是`PATH`而是其他的变量？

**Comment by easyhutu** [comment]
```
#!/bin/bash
set -e
_APPDIR="/usr/lib/any-sync-gui"
export PATH="${_APPDIR}:${PATH}"
export ELECTRON_IS_DEV=0
export LD_LIBRARY_PATH="${_APPDIR}/swiftshader:${_APPDIR}/lib:${LD_LIBRARY_PATH}"
export NODE_ENV=debug
_ASAR="${_APPDIR}/app.asar"
if [[ $EUID -ne 0 ]] || [[ $ELECTRON_RUN_AS_NODE ]]; then
    cd "${_APPDIR}"
    exec electron25 "${_ASAR}" "$@"
else
    cd "${_APPDIR}"
    exec electron25 "${_ASAR}" --no-sandbox "$@"
fi
```

你这样运行下试试呢，因为你是用electron25 app.asar 这种方式运行的，process.resourcesPath获取到的路径默认是/usr/lib/electron25/resources，这个目录程序是没有写权限的。设置export NODE_ENV=debug这个环境变量的目的是将缓存文件的目录设置在当前shell脚本运行的目录上。通常安装打包的deb文件后再运行一般不会出现类似问题

**Comment by zxp19821005** [comment]
非常感谢！
按照您的建议，在脚本中增加了`export NODE_ENV=debug`后，程序运行正常，终端存在报错信息：
```
$ any-sync-gui                                       
cfg file any_sync_cfg.json
resource path resources, dist path: dist
set k, v sysInfo { resource: 'resources', dist: 'dist', listenPort: 8081, env: 'debug' }
[22290:1208/101000.079447:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
[22290:1208/101000.079486:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
write cfg err: [Error: EACCES: permission denied, open 'any_sync_cfg.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'any_sync_cfg.json'
}
read cfg err: [Error: ENOENT: no such file or directory, open 'any_sync_cfg.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'any_sync_cfg.json'
}
read cfg err: [Error: ENOENT: no such file or directory, open 'any_sync_cfg.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'any_sync_cfg.json'
}
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'toString')
    at ReadFileContext.callback (/usr/lib/any-sync-gui/app.asar/server/utils/kvStore.js:70:37)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:325:13)
(node:22290) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'any_sync_cfg.json'
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:22290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22290) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(node:22290) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'any_sync_cfg.json'
(node:22290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
devs: {"dev":null,"devs":[],"pingSecond":1260}
group[1] client[80f5b1247c3d96f78c12849d57906025] connect to server successful!
receive client msg : {"msgEvent":"pingGroup"}
receive[80f5b1247c3d96f78c12849d57906025] msg:{"msgEvent":"pingGroup"}
send group[1] msg:{"msgEvent":"ping"}
receive client msg : {"msgEvent":"ping"}
receive[80f5b1247c3d96f78c12849d57906025] msg:{"msgEvent":"ping"}
online devs: [ '80f5b1247c3d96f78c12849d57906025' ]
```
不知道能不能建议您将`any_sync_cfg.json`的路径更改为`XGD_CONFIG_HOME/Lan同步`?也就是`$HOME/.config/Lan同步`?
还有一个，为了保持程序的兼容性，是否可以考虑使用英文呢？
谢谢！

**Comment by easyhutu** [comment]
> 非常感谢！ 按照您的建议，在脚本中增加了`export NODE_ENV=debug`后，程序运行正常，终端存在报错信息：
> 
> ```
> $ any-sync-gui                                       
> cfg file any_sync_cfg.json
> resource path resources, dist path: dist
> set k, v sysInfo { resource: 'resources', dist: 'dist', listenPort: 8081, env: 'debug' }
> [22290:1208/101000.079447:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: 无此接口“org.freedesktop.portal.FileChooser”
> [22290:1208/101000.079486:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
> write cfg err: [Error: EACCES: permission denied, open 'any_sync_cfg.json'] {
>   errno: -13,
>   code: 'EACCES',
>   syscall: 'open',
>   path: 'any_sync_cfg.json'
> }
> read cfg err: [Error: ENOENT: no such file or directory, open 'any_sync_cfg.json'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'any_sync_cfg.json'
> }
> read cfg err: [Error: ENOENT: no such file or directory, open 'any_sync_cfg.json'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: 'any_sync_cfg.json'
> }
> A JavaScript error occurred in the main process
> Uncaught Exception:
> TypeError: Cannot read properties of undefined (reading 'toString')
>     at ReadFileContext.callback (/usr/lib/any-sync-gui/app.asar/server/utils/kvStore.js:70:37)
>     at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:325:13)
> (node:22290) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'any_sync_cfg.json'
> (Use `electron --trace-warnings ...` to show where the warning was created)
> (node:22290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:22290) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
> (node:22290) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'any_sync_cfg.json'
> (node:22290) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> devs: {"dev":null,"devs":[],"pingSecond":1260}
> group[1] client[80f5b1247c3d96f78c12849d57906025] connect to server successful!
> receive client msg : {"msgEvent":"pingGroup"}
> receive[80f5b1247c3d96f78c12849d57906025] msg:{"msgEvent":"pingGroup"}
> send group[1] msg:{"msgEvent":"ping"}
> receive client msg : {"msgEvent":"ping"}
> receive[80f5b1247c3d96f78c12849d57906025] msg:{"msgEvent":"ping"}
> online devs: [ '80f5b1247c3d96f78c12849d57906025' ]
> ```
> 
> 不知道能不能建议您将`any_sync_cfg.json`的路径更改为`XGD_CONFIG_HOME/Lan同步`?也就是`$HOME/.config/Lan同步`? 还有一个，为了保持程序的兼容性，是否可以考虑使用英文呢？ 谢谢！

第一次运行初始化配置文件可能存在时序问题导致警告报错，后续运行应该就不会报错了

使用英文建议打包前修改[package.json](https://github.com/easyhutu/any-sync-gui/blob/6244cd0308acbf18015cb8c70e7174eb131bf27d/electron_gui/package.json#L4)，productName即打包输出的产物名称

**Comment by zxp19821005** [comment]
收到，谢谢，AUR已更新：https://aur.archlinux.org/packages/any-sync-gui
